#
# Autor.: Joao Rafael F. Bonilha - Foursys
# E-mail.: joao.bonilha@foursys.com.br
# Data_Criacao.: 20/12/2024
#
# Variaveis usadas.:
# GITHUB_TOKEN.: Token de acesso a API do GitHub
#

# Lista todos os repositorios 
name: Listar Repositorios
 
on:
 push:
    branches:
      - main
      - master
 workflow_dispatch:
 
jobs:
  list-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3
 
      - name: Obtendo a lista dos repositorios
        run: |
          ORGANIZATION="rafaelbonilha" # substitua pelo nome da organizacao
          TOKEN="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" # token do usuario/organizacao
          curl -H "Authorization: token $TOKEN" \
          "https://api.github.com/users/$ORGANIZATION/repos?per_page=100" | jq '.[] | {html_url}'           
  
      - name: Listando os repositorios
        run: |
          echo "Repositorios: " \
          jq -r '.[].name' repos.json
          
  # Lista as Tags, se existirem      
  list-tags:
    runs-on: ubuntu-latest
    needs: list-repos
    steps:
      - name: Obter as tags dos repositorios
        run: |
          for repo in $(jq -r '.[].name' repos.json); do
          echo "Obtendo as tags do repositorio: $repo"
          curl -H "Authorization: token ${{ secrets.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}}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository_owner }}/$repo/tags" \
          -o tags_$repo.json
          echo "Tags for $repo:" jq -r '.[].name' tags_$repo.json
          done
