#
# Autor.: Joao Rafael F. Bonilha - Foursys
# E-mail.: joao.bonilha@foursys.com.br
# Data_Criacao.: 20/12/2024
#
# Variaveis usadas.:
# GITHUB_TOKEN.: Token de acesso a API do GitHub
#
- name: Gerar lista de Repositorios
  on:
    workflow_dispatch:
      inputs:
        GITHUB_TOKEN:
          required: true
          type: string
 
  jobs:
    list-tags:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repositorio
      uses: actions/checkout@v2
 
    - name: Listar repositorios e suas tags
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/rafaelbonilha/repos | jq -r '.[].name' | while read repo; do
          echo "Repository: $repo"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/rafaelbonilha/$repo/tags | jq -r '.[].name'
        done
