#
# Autor.: Joao Rafael F. Bonilha - Foursys
# E-mail.: joao.bonilha@foursys.com.br
# Data_Criacao.: 20/12/2024
#
# Variaveis usadas.:
# GITHUB_TOKEN.: Token de acesso a API do GitHub
#

# Lista todos os repositorios 
name: Listar Repositorios
 
on:
 push:
    branches:
      - main
      - master
 workflow_dispatch:
 
jobs:
  list-repos:
    runs-on: ubuntu-latest
    steps:
    - name: Listar Repos
      uses: actions/github-script@v6
      with:
         script: |
            const username = 'NOME_DO_USUARIO'; // Substitua pelo nome de usuário desejado
            let allRepos = [];
            let page = 1;

            while (true) {
              const repos = await github.rest.repos.listForUser({
                username: username,
                per_page: 100, // Máximo permitido pela API
                page: page,
              });

              if (repos.data.length === 0) {
                break; // Não há mais repositórios
              }

              allRepos = allRepos.concat(repos.data);
              page++;
            }

            if (allRepos.length > 0) {
              console.log(`Repositórios de ${username}:`);
              for (const repo of allRepos) {
                console.log(`- ${repo.name} (${repo.html_url})`);
              }
            } else {
              console.log(`O usuário ${username} não possui repositórios públicos.`);
            }
          
  # Lista as Tags, se existirem      
 # list-tags:
  #  runs-on: ubuntu-latest
  #  needs: list-repos
   # steps:
   #   - name: Obter as tags dos repositorios
   #     run: |
   #       for repo in $(jq -r '.[].name' repos.json); do
   #       echo "Obtendo as tags do repositorio: $repo"
   #       curl -H "Authorization: token ${{ secrets.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}}" \
   #       -H "Accept: application/vnd.github.v3+json" \
   #       "https://api.github.com/repos/${{ github.repository_owner }}/$repo/tags" \
   #       -o tags_$repo.json
   #       echo "Tags for $repo:" jq -r '.[].name' tags_$repo.json
   #       done
